fix(exchange/server): use named field parameters
panates/hl7v2 pull request #34
Opened 2022-06-25 01:13 UTC by fauxsoup

Indexes of certain field parameters appear to have changed in some revisions of the HL7 specification. Using the named properties instead of the indexes circumvents the difference in indexing between versions.

Needs evaluation for correctness.

I discovered this error when using `HL7Server` to receive an HL7 v2.7 observation results message (`ORU^R01^ORU^R01`) that was previously generated by `v0.9.0` of this library and throwing from the event handler. This triggers an error acknowledgement, which then attempts to construct an ERR segment using indexes.

Starting in HL7 v2.5, the ERR segment was drastically altered, and the path that was used no longer references what it did in previous iterations. Instead, the path used in the original code path maps to a `Severity` field, which does not contain any sub-structures.

I doubt this fix is correct for all use cases, but works with 2.5+ AFAICT. Happy to implement a complete solution if I can get some guidance.

2022-06-25 08:06 UTC, erayhanoglu commented
Hello. Thank you for your feedback. It looks like this patch will break versions prior to 2.5. And library will be useless. Version of the HL7 message can be checked before creating ERR segment.

2022-06-27 14:43 UTC, fauxsoup commented
Okay. I will fork the construction of the ERR segment based on the version identifier.

2022-06-27 14:47 UTC, fauxsoup commented
@erayhanoglu would you be okay with adding `semver` as a dependency? If not, I will do some custom logic to parse the version so we can do a comparison.

2022-06-28 05:39 UTC, erayhanoglu commented
I think you dont need the `semver` to compare HL7 versions. "String compare" will do the job. 
```js
if (msg.version<'2.5')
 ...
```

2022-06-28 05:49 UTC, erayhanoglu requested changes
This patch will break versions below 2.5.. So version compare could be made.

2022-07-01 20:40 UTC, fauxsoup commented
Rebased and applied the suggested fork in logic, restoring the pre-2.5 version where appropriate.

2022-07-05 10:02 UTC, merged

2022-07-05 10:06 UTC, erayhanoglu commented
Released v0.13.0